title:               Blaulichtplaner Blog
url:                 https://blog.blaulichtplaner.de
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle' , '*.sh']

permalink:           /:categories/:slug:output_ext
paginate:            5
paginate_path:       /blog/:num

collections:
  handbuch:
    output: true
    permalink: /:collection/:name
    sort_by: section

blog:
  truncated_preview: true

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              MedPlan Solutions GmbH
  url:               blaulichtplaner.de
  email:             info@blaulichtplaner.de

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist