title:               Blaulichtplaner Blog
url:                 https://blog.blaulichtplaner.de
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           /:categories/:slug:output_ext
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              MedPlan Solutions UG
  url:               blaulichtplaner.de
  email:             info@blaulichtplaner.de

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist